### ISSUE TITLE
Incomplete installation manual

### ISSUE THREAD

**Issue by PavelVesely** [algbio/matchtigs#2]
I have successfully installed matchtigs using cargo on WSL (Linux in Windows). Greedytigs and Eulertigs both work fine (at least in that their computation is relatively fast). However, optimal matchtigs fail since I don't have blossom5 installed (I suppose it's a program based on [Kolmogorov's paper from 2009](https://link.springer.com/article/10.1007/s12532-009-0002-8)).

Could you provide a manual for blossom5 installation? It doesn't seem to be a standard package / program that can be installed using apt-get or cargo.

Another (related) issues is that the installation using conda 22.9.0 fails, that is, running matchtigs from conda results in the following output (for any arguments):
```
--debug-print-graphtrue

  '?'
```

This apparently happens not only under WSL as my colleague had a similar issue on Linux.

**Comment by sebschmi** [comment]
Unfortunately, blossom V is commercial software, that is freely available only to researchers. You can request it from e.g. the blossom V author.

For the second problem, which version of matchtigs have you installed?

**Comment by PavelVesely** [comment]
Thanks for the answer!

For the issue with installation from conda, I have matchtigs version 1.3.1. The matchtigs from cargo is version 1.5.3 (and it works, at least for greedy-matchtigs and eulertigs).

**Comment by sebschmi** [comment]
That's strange. For me, both version 1.3.1 and 1.5.3 work fine from conda. I am using the following environment:

```
name: testmt
channels:
        - conda-forge
        - bioconda
dependencies:
        - matchtigs == 1.3.1
```

**Comment by sebschmi** [comment]
Ah well, I am using a different version of mamba/conda:

```
$ mamba --version
mamba 0.25.0
conda 4.13.0
```

maybe there lies the issue?

**Comment by PavelVesely** [comment]
This seems like a plausible cause of the second part of the issue. Unfortunately I'm not easily able to get an up-to-date conda/mamba now. I will close the issue.
